import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Molecules/navbar";
import Footer from "./components/Molecules/Footer";
import { ThemeProvider } from "./components/Atoms/ThemeProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen flex flex-col `}
        >
          <Toaster />
          <Navbar />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
