export type Listing = {
  id: string;
  title: string;
  asset_type: 'property' | 'vehicle';
  price_usdc: string;
  status: 'open' | 'pending' | 'sold';
  listing_type: 'owner_direct' | 'agent_brokered';
  created_by: string;           // user id of the listing agent (or owner for owner_direct)
  agent_name: string;
  agent_kyc: 'verified' | 'pending';
  agent_address?: string;

  // agent_brokered only — the off-platform owner whose wallet is auto-generated by the backend
  owner_name?: string;
  owner_email?: string;
  // 'pending_email' = invitation sent, awaiting owner's confirmation click
  // 'confirmed'     = owner confirmed → listing is live
  owner_status?: 'pending_email' | 'confirmed';

  commission_bps?: number;    // e.g. 500 = 5%
  location: string;
  description: string;
  bedrooms?: number;
  bathrooms?: number;
  year?: number;
  mileage?: string;
};

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: '3 Bedroom Duplex, Lekki Phase 1',
    asset_type: 'property',
    price_usdc: '120,000',
    status: 'open',
    listing_type: 'agent_brokered',
    created_by: 'user-1',
    commission_bps: 500,
    owner_status: 'pending_email',
    agent_name: 'John Adeyemi',
    agent_kyc: 'verified',
    agent_address: '0x1a2b...3c4d',
    location: 'Lekki, Lagos',
    description: 'Spacious 3-bedroom fully detached duplex in a serene estate. 24/7 security, backup power, and BQ. Close to the Lekki-Epe expressway.',
    bedrooms: 3,
    bathrooms: 3,
  },
  {
    id: '2',
    title: '2021 Toyota Land Cruiser V8',
    asset_type: 'vehicle',
    price_usdc: '58,000',
    status: 'open',
    listing_type: 'owner_direct',
    created_by: 'user-2',
    agent_name: 'Amaka Osei',
    agent_kyc: 'verified',
    location: 'Abuja, FCT',
    description: 'Foreign-used 2021 Land Cruiser V8. Full option, 7 seater, sunroof, leather interior. Accident-free. Papers intact.',
    year: 2021,
    mileage: '32,000 km',
  },
  {
    id: '3',
    title: '5 Bed Mansion, Old Ikoyi',
    asset_type: 'property',
    price_usdc: '480,000',
    status: 'open',
    listing_type: 'agent_brokered',
    created_by: 'user-3',
    commission_bps: 300,
    owner_status: 'confirmed',
    owner_name: 'Chukwuemeka Balogun',
    owner_email: 'emeka.b@gmail.com',
    agent_name: 'Emeka Okafor',
    agent_kyc: 'verified',
    location: 'Ikoyi, Lagos',
    description: 'Luxurious 5-bedroom fully-detached mansion. Private pool, gym, cinema room, 4-car garage. On a quiet cul-de-sac.',
    bedrooms: 5,
    bathrooms: 6,
  },
  {
    id: '4',
    title: '2023 Mercedes-Benz GLE 450',
    asset_type: 'vehicle',
    price_usdc: '95,000',
    status: 'pending',
    listing_type: 'owner_direct',
    created_by: 'user-4',
    agent_name: 'Fatima Al-Hassan',
    agent_kyc: 'verified',
    location: 'Port Harcourt, Rivers',
    description: 'Brand new 2023 GLE 450 4MATIC. Zero mileage. Full option. AMG sport package. Lagos clearance papers.',
    year: 2023,
    mileage: '0 km',
  },
  {
    id: '5',
    title: 'Commercial Plaza, Victoria Island',
    asset_type: 'property',
    price_usdc: '850,000',
    status: 'open',
    listing_type: 'owner_direct',
    created_by: 'user-5',
    agent_name: 'Bisi Lawson',
    agent_kyc: 'verified',
    location: 'Victoria Island, Lagos',
    description: '4-floor commercial plaza with retail ground floor and 3 office floors. Fully leased. ROI of 12% p.a. Excellent for investment.',
    bedrooms: 0,
    bathrooms: 8,
  },
  {
    id: '6',
    title: '2020 Range Rover Sport HSE',
    asset_type: 'vehicle',
    price_usdc: '72,000',
    status: 'open',
    listing_type: 'owner_direct',
    created_by: 'user-1',
    agent_name: 'John Adeyemi',
    agent_kyc: 'verified',
    location: 'Lekki, Lagos',
    description: 'Foreign-used 2020 RR Sport HSE Dynamic. Panoramic roof, heated seats, diesel. Full service history. DU.',
    year: 2020,
    mileage: '48,000 km',
  },
];
